import Head from 'next/head'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Food Delivery Service</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
          main
      </main>

      <footer className="">
          Build by alpha69
      </footer>
    </div>
  )
}
