import Head from 'next/head'

export default function Home() {
  return (
		<div className="px-10 bg-yellow-200">
			<Head>
				<title>Food Delivery Service</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header className="">
				<nav>
					<svg
						className="w-12 h-12 text-4xl"
						fill="none"
						stroke="currentColor"
						viewBox="0 0 24 24"
						xmlns="http://www.w3.org/2000/svg"
					>
						<path
							strokeLinecap="round"
							strokeLinejoin="round"
							strokeWwidth="2"
							d="M4 6h16M4 12h16M4 18h16"
						></path>
					</svg>
          <h1> <span>Order</span> Something</h1>
          <div>
            <input type="text" placeholder="Search"/>
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path strokelinecap="round" strokelinejoin="round" strokewidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
            </svg>
          </div>
				</nav>
			</header>
			<main className="">main</main>

			<footer className="">Build by alpha69</footer>
		</div>
  );
}
